backend:
  name: github
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://sandbox.pedrohenri.design/
  auth_endpoint: /api/auth
  repo: andrevandal/pedrohenri.design

media_folder: public/images/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /images/uploads # The src attribute for uploaded media will begin with /images/uploads

slug: 
  encoding: ascii
  clean_accents: true

collections:
  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    create: true
    slug: "{{title}}"
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "string"
        label: "Posts"
        folder: "content/posts"
        create: true
        slug: "{{slug}}"
        editor:
          preview: false
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Cover"
            name: "cover"
            widget: "object"
            summary: "{{fields.source}}: {{fields.alternativeText}}"
            fields:
              - label: "image"
                name: "image"
                widget: "image"
                allow_multiple: false
                choose_url: false
              - label: "Alternative Text"
                name: "alternativeText"
                widget: "string"
                required: false
              - label: "Source"
                name: "source"
                widget: "string"
                required: false
          - label: "Description"
            name: "description"
            widget: "text"
            required: false
          - label: "Draft"
            name: "draft"
            widget: "boolean"
            default: true
          - label: "Categories"
            name: "categories"
            widget: "relation"
            collection: "categories"
            search_fields: ["title"]
            value_field: "{{slug}}"
            display_fields: ["title"]
            multiple: true
            max: 1
          - label: "updated at"
            name: "updatedAt"
            widget: "datetime"
            required: false
          - label: "created at"
            name: "createdAt"
            widget: "datetime"
          - label: "Body"
            name: "body"
            widget: "markdown"
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Cover"
        name: "cover"
        widget: "object"
        summary: "{{fields.source}}: {{fields.alternativeText}}"
        fields:
          - label: "image"
            name: "image"
            widget: "image"
            allow_multiple: false
            choose_url: false
          - label: "Alternative Text"
            name: "alternativeText"
            widget: "string"
            required: false
          - label: "Source"
            name: "source"
            widget: "string"
            required: false
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: true
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        search_fields: ["name"]
        value_field: "{{slug}}"
        display_fields: ["name"]
      - label: "Categories"
        name: "categories"
        widget: "relation"
        collection: "categories"
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        multiple: true
        max: 1
      - label: "updated at"
        name: "updatedAt"
        widget: "datetime"
        required: false
      - label: "created at"
        name: "createdAt"
        widget: "datetime"
      - label: "Body"
        name: "body"
        widget: "markdown"